Repository apolloconfig/agollo, pull requests merged in 2019-12, with the labels that each got.

#86 Fix version semantic errors #83
  CONTRIBUTING.md
  go.mod
  parser.go
  repository.go
  start.go
Labels: enhancement

#87 [Feature]增加控制缓存配置的开关
  agcache/cache.go
  agcache/default.go
  app_config.go
  change_event.go
  change_event_test.go
  component_common.go
  component_common_test.go
  componet_notify.go
  componet_notify_test.go
  config_server_test.go
  file.go
  file_test.go
  json_config.go
  json_config_test.go
  log.go
  log_test.go
  notify_server_test.go
  parser.go
  repository.go
  repository_test.go
  request.go
  request_test.go
  start_test.go
Labels: bug, enhancement

#89 修复并发问题
  repository.go
Labels: bug

#91 optimize usage of allNotifications
  app_config.go
  componet_notify.go
  repository.go
  start.go
Labels: bug
